{"uuid": "35ae55e0-a7d4-4c43-bcde-e22308fe07b4", "children": ["0e20c0e2-2adf-4119-94b2-53a8e69068eb"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/home/vladimir/Develop/final_project_duo/tests/logs/test_one.log'\n", "trace": "  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/vladimir/Develop/final_project_duo/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/vladimir/Develop/final_project_duo/conftest.py\", line 40, in browser\n    file_handler = logging.FileHandler(f\"logs/{request.node.name}.log\")\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1147, in __init__\n    StreamHandler.__init__(self, self._open())\n  File \"/usr/lib/python3.8/logging/__init__.py\", line 1176, in _open\n    return open(self.baseFilename, self.mode, encoding=self.encoding)\n"}, "start": 1660757338239, "stop": 1660757338239}], "start": 1660757338239, "stop": 1660757338310}